### ISSUE TITLE
Delete test-files after running test

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#11]
The test creates many annyoing random files in the project directory.
It would be great, if those files were deleted after running the test.

**Comment by jGleitz** [comment]
Speaking of Sheet 6 Task C, that's exactly what the test does on my machine.

There is a method for it tagged with the @AfterClass Annotation. Maybe you could look at it and make and educated guess why it's not working for you.

**Comment by RomanLangrehr** [comment]
I'm talking about Sheet 6 Task C.
The code to delete the created files is executed, but file.delete() returns false. I don't know why.

**Comment by jGleitz** [comment]
0301d32725457b692fcc6c963b3d5a61f03740da as well contains a possible fix for this bug. I switched to use `file.deleteOnExit()`. I have the feeling that it's faster (hard to tell on a SSD). And maybe this will fix it for you.

If it does not, I would ask you to try to find out why it's not working. Debuggin an issue I don't even have is hard.

**Comment by RomanLangrehr** [comment]
This fixed the problem. Thanks

**Comment by jGleitz** [comment]
Great to hear. I'm curious, what was the problem and how did you fix it?

**Comment by RomanLangrehr** [comment]
Actually i saw right now it isn't fixed. Probably deleting the files only works sometimes ?!

**Comment by RomanLangrehr** [comment]
Ok, this was my fault. Deleting the files works fine, except when you abort the test (e.g. when you found the bug while debugging) (Of course!)
I'm really sorry for that.
