### ISSUE TITLE
final2: Error messages for wrong `print` outputs do not reveal the preceding commands

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#114]
E.g.:

```
java.lang.AssertionError: We ran a session on your interactive console
 with the following input file:

0000
0*00
0R00
0000

 running the commands 

print
move 1
print
move 1
print
move 1
print
move 1
print
quit

but got unexpected output:
the first error occurred for command
print

 First error at line 2:
Expected: is "r300"
     but: was "0300"
```

The error message does not tell me which print command failed.
A solution would be to print all commands run prior to the error.
A bit related to #39.

**Comment by jGleitz** [comment]
Another solution would be to give the commands line numbers and add the line number to the “the first error occurred for command“

**Comment by jGleitz** [comment]
Do you think the solution in #118 is sufficient? Or would adding the preceding commands, like you proposed be better?

**Comment by pcworld** [comment]
Yes I think your solution is fine.
