### ISSUE TITLE
quit using incomplete

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#116]
I thought maybe we could quit adding an always failing `incomplete` method. We could rather only move the tests to `master` if they seem to be mature enough. What do you think?

**Comment by pcworld** [comment]
+1. Those incomplete methods were annoying to me.

**Comment by RomanLangrehr** [comment]
Sounds like a pretty good idea...

**Comment by jGleitz** [comment]
Alright.
