### ISSUE TITLE
Failing FrameworkTest

### ISSUE THREAD

**Issue by kelunik** [jGleitz/JUnit-KIT#117]
There's currently only one failing test: `FrameworkTest`:
http://paste.jesse-obrien.ca/1RKB

Why does that test fail? What does it actually test?

**Comment by jGleitz** [comment]
Woah. This should not fail. (It does not fail on my machine).

Have you set `-DclassName=test.test.TestClass` in the VM arguments?

**Comment by kelunik** [comment]
Oh, right, I just forgot to exclude them so only those in `final2` run, thanks.
With `-DclassName=test.test.TestClass` they're passing.
