### ISSUE TITLE
Case Insensitivity During Insertion

### ISSUE THREAD

**Issue by MartinLoeper** [jGleitz/JUnit-KIT#12]
The task states to ignore case sensitivity during insertion. Does that mean that we should insert the attributes as they are given or are we allowed to convert them to lower case?

**Comment by RomanLan** [comment]
I think we are allowed to convert them to lower case.

**Comment by jGleitz** [comment]
I don't quite get what are you asking. Are you talking about how the tests set up the test input files or how the tested class may handle input files?

**Comment by MartinLoeper** [comment]
Ah, I think I got it...
The output has to be lower case.
"Alle Zeichen der Ausgabe sind kleingeschrieben."

So one is allowed to execute toLowerCase() on every input string.

**Comment by jGleitz** [comment]
Furthermore: One is expected to do so.
But as we are testing the Strings with the `is(...)` Matcher, we assert that, too.
