### ISSUE TITLE
Add Create Test

### ISSUE THREAD

**Issue by acBerger** [jGleitz/JUnit-KIT#127]
Test for command "create ant,x,y" should be added.

**Comment by RomanLangrehr** [comment]
I think we should test here, whether the program does not exist, when only an "later" created ant is left on the playing field.
And if later created ants are removed correctly.

**Comment by jGleitz** [comment]
> whether the program does not exist

Testing whether a program exists is quite a new task ;) Assuming you meant "exits", I agree.

**Comment by RomanLangrehr** [comment]
I think with #160 we tested create enough, so I'll close this.

**Comment by pcworld** [comment]
You probably meant #162

**Comment by RomanLangrehr** [comment]
No, to put things clear:
When #160 is done, we tested the sufficiently tested the create command. So I closed this issue, to avoid having to issues for the same problem.
