### ISSUE TITLE
Add InvalidInputFile Test

### ISSUE THREAD

**Issue by acBerger** [jGleitz/JUnit-KIT#129]
Test for InvalidInputFiles as not recatangular board or no ants should be added.

**Comment by pcworld** [comment]
We should still test for
- preceding/trailing whitespace
- I'd suggest to replace the 7 in the following test with a 5, because that's near the limit and some people might have mixed up `<` and `<=`:  
  <pre>
  000
  700
  000
  </pre>

**Comment by jGleitz** [comment]
I agree with both.
