### ISSUE TITLE
Add Quit Test

### ISSUE THREAD

**Issue by acBerger** [jGleitz/JUnit-KIT#130]
Test for command "quit" should be added.

**Comment by RomanLangrehr** [comment]
I think the tests for the ant command are sufficient.

**Comment by jGleitz** [comment]
> I think the tests for the ant command are sufficient.

Wrong topic ;)

Nevertheless, this can be closed.

**Comment by RomanLangrehr** [comment]
Not the wrong topic, just an copy-paste-mistake ;)

Am 2015-03-26 um 22:56 schrieb Joshua Gleitze:
