### ISSUE TITLE
Program must exit when all ants have left the field

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#142]
For the `move` command, there are at least three different cases to test:
- speedup=1, repeatedly run `move 1` until you expect all ants to have left
- speedup=1, run `move` with a high count
- use a high speedup factor (with sporty ants) and only run `move 1` once

We also have to test this for the `escape` command.

**Comment by pcworld** [comment]
I don't think all four listed cases are tested yet. At least EscapeTest does not test for program exit after `escape`; I haven't reviewed yet if you test all three `move` cases in #155.

**Comment by jGleitz** [comment]
`escape` will be done, but the issue for that is #128. I thought I covered everything for `move`.

**Comment by pcworld** [comment]
Okay then. Reviewing if all three "move" cases are tested is part of #166 then.
