### ISSUE TITLE
Tests with empty lines at the end of the input file

### ISSUE THREAD

**Issue by takeshior** [jGleitz/JUnit-KIT#147]
First of all, I would like to thank you for taking you time to develop this great project.

I'm not 100% sure, but I think when using the FileInputHelper provided by IPD/ITI empty lines at the EOF won't become part of the returned array. Therfore its not possible to throw an error for 2 of the bad input file tests.

**Comment by pcworld** [comment]
Hi, this has been discussed in #61 before. [The official statements](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53432&pos_pk=196620&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#196620) on ILIAS for final1 sound like our tests are correct.

**Comment by chrisliebaer** [comment]
I'd recommand replacing the given FileInputHelper. The same can be achieved with a few lines and a Scanner. See: http://docs.oracle.com/javase/7/docs/api/java/util/Scanner.html

The specification is pretty clear about the file formatting. While you might get away with using the given Helper class you are running into problems if using your own implementation, so removing or changing the tests would fail to detect wrong implementations (other than the provided one).

**Comment by RomanLangrehr** [comment]
Those tests were already added in #136

**Comment by pcworld** [comment]
> Those tests were already added in #136

The OP _complained_ about these tests, not wanted them to be created.

**Comment by RomanLangrehr** [comment]
Oh, sorry.
But we had the same discussion in the last project, so I keep this closed.
https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53432&pos_pk=196439&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#196439

**Comment by takeshior** [comment]
Thank you for your fast responses (shame on me for ignoring the old issue). An own implementation is probably the way to go...

**Comment by pcworld** [comment]
If we really want to go deeper in interpretation of German language, there's a [new statement on trailing empty lines](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&pos_pk=197721&thr_pk=53871&offset=0&viewmode=1&cmd=markPostRead&cmdNode=ed:5v&baseClass=ilRepositoryGUI#197721) regarding final2:

> … können Sie als Fehler werten weil Zeilen der Länge 0 existieren

Note "können" here: It might be optional and not required.
Though I don't think they write their sheets and forums answers with as much thought and detail as we usually try to interpret them with :)

**Comment by jGleitz** [comment]
> Though I don't think they write their sheets and forums answers with as much thought and detail as we usually try to interpret them with

Which I think is a bad thing. Because they made us take GBI. And after GBI, you just can't help but think every definition down to every possible edge case and different meaning. Meanwhile, most things they say are quite ambiguous.

My 2 cents: "Können" means in that case that this is the recommended behaviour but it will not be tested by Praktomat.

**Comment by jGleitz** [comment]
In [Befehle Anzahl von Leerzeichen/Kommas](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53431&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI) they state regarding whitespace in commands:

> Weil die Aufgabe dies aber nicht thematisiert, ist es am sichersten, diese nicht zu akzeptieren.

I extended that to trailing newlines. For final task 1, we had a [detailed statement](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53432&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI) not to accept trailing newlines.

**Comment by jGleitz** [comment]
What to do with this? I think having a test for it is not a bad thing. I suspect it's the expected behaviour. And even if we make some people change their implementations because of our tests, this will do them no harm.

**Comment by pcworld** [comment]
I agree.
It might be helpful to add a comment to the test that failing it might be result of using FileInputHelper and add a link to the relevant ILIAS discussions.

**Comment by jGleitz** [comment]
Yeah, that's true. Can you do that?
