### ISSUE TITLE
Test input file whitespace handling

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#151]
We should have an error test for boards that are completely correct except for leading or trailing whitespace in one of the rows.

**Comment by pcworld** [comment]
As far as I can see in https://github.com/jGleitz/JUnit-KIT/pull/153/files#diff-1e3d936ed34460363dd24c0c522427e1R237, ignoring the spaces the fields are actually _invalid_, because the rows have differing number of columns when ignoring the spaces.

**Comment by jGleitz** [comment]
That's true. So this is still open.
