### ISSUE TITLE
Create & Move

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#160]
We should check whether newly created ants move correctly.
Especially for athletic and lazy ants...

**Comment by jGleitz** [comment]
I thought we could move the test run containing all types from #155 to `LangtonTest`, then run it but add all except of one ants through `create`.

**Comment by jGleitz** [comment]
This would allow a short test to assert the correct behaviour for all types.

**Comment by RomanLangrehr** [comment]
Okay, thats a good idea. I didn't wrote many tests, yet.
Do you think, there is a better way of copy&paste (and modify) this?

**Comment by jGleitz** [comment]
> Do you think, there is a better way

Yep, moving the input file and the pitches to LangtonTest. We can do this once #155 is merged.

**Comment by jGleitz** [comment]
You would not guess, but this actually screwed my program, while all other test succeeded!

**Comment by jGleitz** [comment]
> his actually screwed my program

not quite, but a bug in the test I wrote made my find bug in my implementation.
