### ISSUE TITLE
Is a + in speedup or rule really an error?

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#164]
I'm not sure whether we're really allowed to expexct an error message for an `"+"` in the speedup and rule command line argument. Here's why:

The task sheet defines the following for the speedup argument:

> _value_ ist ein Platzhalter für eine positive Integerzahl ab 1

It depends heavily on what you define as an Integer. But you could argue that they most likely refer to Java's definition of an Integer. And as `Integer#parseInt` accepts tokens like `+12`, it's a valid Java-Integer.

Regarding the rule, I'm quite sure that `+12` was never meant to be accepted. **But** 

> Die Bewegungsrichtungen in einer Regel stammen aus der Menge {45, 90, 270, 315}

can be interpreted in two ways:
- Tokens defining a direction have to be out of the set _of symbols_ `{"45", "90", "270", "315"}`
- Integer values defining a direction have to be out of the set _of numbers_ `{45, 90, 270, 315}`

In the second interpretation, you could once again argue that `"+45"` means the Java-Integer `45` and `45 ∈ {45, 90, 270, 315}`.

Remember that time when Mr. Worsch warned us to always distinguish between symbols and their meaning? ;)

**Comment by pcworld** [comment]
I thought about this too. An ILIAS question might be good.

Re `rules=`: From section B:

> Eine      Regel      ist      eine      Sequenz der        Elemente        der        Menge        {45,        90,        270,        315},        die        jeweils        durch        einen        Bindestrich        separiert        sind.   

So I think this set is a set of symbols, not integers.

**Comment by jGleitz** [comment]
Yep, that's a good point. I wish they adopted Mr. Worsch's pattern to style symbols differently…

**Comment by jGleitz** [comment]
similar to #165, you could argue the same for command parameters!

**Comment by pcworld** [comment]
@kelunik mentioned in #171:

> https://github.com/jGleitz/JUnit-KIT/blob/ant-development/src/final2/subtests/InvalidCommandLineArgumentsTest.java#L130
> 
> I think that's not something that should error. `+12` is a valid integer.

**Comment by pcworld** [comment]
I'm currently leaning towards the following interpretation:
Allow and explicitly test for leading zeros and `+` in all commands and in `speedup`, but disallow and explicitly test leading zeros and `+` in `rule`. My reason for the latter is that rules like `+45-+45-+45-+45-00045` look really awkward and presumably weren't intended to be valid.

**Comment by jGleitz** [comment]
See [Führende Nullen und +](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53901&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI) on KIT-ILIAS.

**Comment by pcworld** [comment]
Thanks for creating the question. [As per the response](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53901&pos_pk=197762&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#197762), this won't be tested by Praktomat, so we shouldn't (re)include it in our tests.
