### ISSUE TITLE
Leading zeros

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#165]
I think leading zeros are allowed in
- speedup
- rule
- command arguments
  so we should test for that.

**Comment by jGleitz** [comment]
This is very close to #164! It highly depends whether they're talking about symbols or numbers.

**Comment by pcworld** [comment]
> This is very close to #164! It highly depends whether they're talking about symbols or numbers

I guess leading zeros is only an issue for the `rules=` command, as they possibly define a set of symbols there.
(Which makes me rather uncertain whether `move +1` really is an error, if `move 01` was allowed…)

**Comment by jGleitz** [comment]
If `move 01` is allowed, you can't really argue to permit `move +1`, I think. Same for speedup and rule.

**Comment by jGleitz** [comment]
See [Führende Nullen und +](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53901&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI) on KIT-ILIAS.

**Comment by pcworld** [comment]
[As per the response](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53901&pos_pk=197762&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#197762), this won't be tested by Praktomat, so we shouldn't include it in our tests.
