### ISSUE TITLE
Unable to debug with breakpoints because of timeout

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#17]
It is impossible to debug with breakpoints, because when the program stops at a breakpoint you usually need much more than 5 seconds to continue, but after 5 seconds the test fails cause of the timeout after 5 seconds.

**Comment by jGleitz** [comment]
For Eclipse:
The run configuration you use for the test has the Option _Keep JUnit running after a test run when debugging_. Activating it fixes the issue for me.

**Comment by RomanLangrehr** [comment]
Works for me as well, thanks

**Comment by chrisliebaer** [comment]
This checkbox has sideffects. JUnit still terminates and leaves the instance running. For some strange reason I get IOExceptions if the test failes before my application finished reading the input file. I would not recommend the approach above.

**Comment by jGleitz** [comment]
@Lupinus I can only partly reproduce this behaviour. That's what happens on my machine:
- The test fails and terminates regardless of the option. That's correct. Meanwhile, I'm still able to debug the test method my breakpoint got activated for and solve my error.  I have to rerun the test afterwards, which is not really bad.
- Input files do not get deleted. This is a known bug that might be fixed. To get it fixed, somebody has to find this significant enough to file a new (!) issue for it.

I don't know why you get those IOExceptions, but would be very interested if you'd investigate further. If it is something we can fix, we will. If you want to talk about it, please open a new issue.

**Comment by jGleitz** [comment]
Added _wontfix_ as we cannot address the way JUnit behaves when debugging. This would require writing our own unit test library, which obviously is too much.

If you want to address the issues of the IOException or the input files not getting deleted, feel free to file new issues for them.

**Comment by chrisliebaer** [comment]
The exception is only raised if the new Java7 Files.readAllBytes is used.

```
new String(Files.readAllBytes(Paths.get(filePath)));
```

I've been using this as workaround during development the package is outside the allowed scope so it doesn't really matter. I recommend increasing the timeout during debugging just in case there are other things that are affected by this option. No need to investigate further in my opinion.

**Comment by jGleitz** [comment]
Now that's a nice idea. See #78.

**Comment by jGleitz** [comment]
I think  8d5b88d / #88 provides a sufficient solution for everyone, as the timeout is now configurable through the run configuration and can even be disabled completely.
