### ISSUE TITLE
direction command: northwest can be `SW`

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#182]
The task sheet defines the mapping as follows: `Südwest        =        SW        und        Nordwest        =        SW`
[According to an official statement](https://ilias.studium.kit.edu/ilias.php?ref_id=413546&cmdClass=ilobjforumgui&thr_pk=53116&pos_pk=197760&offset=0&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI#197760), both `NW` and `SW` is valid output of `direction` when an ant looks northwest.

**Comment by jGleitz** [comment]
#186 

> "Fixes" #182 by a less brutal method called "documentation".
