### ISSUE TITLE
Check invalid commands - Task A

### ISSUE THREAD

**Issue by MartinLoeper** [jGleitz/JUnit-KIT#19]
We have to test invalid interactive commandline entries.
E.g. search (without param)
        quit (with param)
        info (with param)
       some-invalid-command

**Comment by jGleitz** [comment]
This is already implemented for Task C (look at `BasicCommandsTest`). Editing this to concerning only Task A

**Comment by MartinLoeper** [comment]
Sorry, that was my fault. I am not at home and thus using the mobile version of github which is in fact difficult to overlook (plus the annoying spelling correction by Android).

**Comment by jGleitz** [comment]
No need to be sorry. I feel your pain, getting work done is hard on mobile.

**Comment by RomanLangrehr** [comment]
I added a test for quit with arg, the other tests were already implemented.
I think with have all cases for wrong input commands now.

**Comment by jGleitz** [comment]
88238be1e4d7abd70a7fc17c9c9c3d89c192cc6e
