### ISSUE TITLE
[06-C] Test illegal search terms

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#24]
We should test illegal search terms in task C.

**Comment by jGleitz** [comment]
988d39cca32b4a882aa4ff161aec1a01b0bf2710

**Comment by jGleitz** [comment]
@RomanLan would you consider `SearchTermParsingTest` as complete enough to remove the `incomplete` fail method?

**Comment by RomanLangrehr** [comment]
@jGleitz Yes, think we test all important cases.
