### ISSUE TITLE
6 A: empty file is "nicht erlaubt"

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#28]
The test for 6 A performs a search on an empty file. While this is nice (and should not break any implementation), the task sheet states _“Außerdem sind leere Eingabetexte nicht erlaubt.”_. Therefore, our test obviously has wrong expectations. **But**: Does that mean we should expect an error message, or can we assume that an empty file is never passed?

**Comment by RomanLangrehr** [comment]
I think we should delete this test.
But we don't test any wrong input files at A. Can we assume, that all input files are correct?

**Comment by MartinLoeper** [comment]
I think, we can assume that all input files are correct, thus not doing tests which are excluded by the task.
Nevertheless I prefer to cover all cases (within the meaning of fail-fast).

**Comment by jGleitz** [comment]
I am quite surprised that they expect extensive error checking in C but don't seam to care about that in A.
