### ISSUE TITLE
final1: Thoughts on circles

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#35]
[Quote from wiki](https://github.com/jGleitz/JUnit-KIT/wiki/Final-Task-1-–-Recommendation):

> I'm not exactly sure, but I think the following is valid and not to be interpreted as a circle:
>     <pre>A(id=1) successor-of B(id=2)
> B(id=2) predecessor-of C(id=3)
> C(id=3) predecessor-of A(id=1)</pre>
>     Should be a good fit for a test case, since originally I interpreted such a graph as a circle, however now that I read the ILIAS comments more closely, this could be valid.

Your thoughts?

**Comment by jGleitz** [comment]
That is definitely neither a circle nor a semamtic error. Thinking about it, my current implementation would likely fail on it, too. 
So we should definitely have a test for it. As some implementations may treat different relations differently, we should assert the behavior for all six, as we're already doing for circles.

**Comment by pcworld** [comment]
> As some implementations may treat different relations differently, we should assert the behavior for all six, as we're already doing for circles.

Note that this is not yet implemented in [pull 37](https://github.com/jGleitz/JUnit-KIT/pull/37).

**Comment by jGleitz** [comment]
> Note that this is not yet implemented in pull 37.

I'm opening a new issue for this.
