### ISSUE TITLE
Should we move TODO to Issues?

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#36]
@pcworld added tons of useful ideas for tests to the Wiki. Initially I thought it would be nice to keep track of things there.
On the other hand, having comments and assign options here in issues is nice. So should we start filing issues for the TODO list instead of updating the wiki?
If yes, I'd volunteer to move the current wiki to the issues section.

**Comment by pcworld** [comment]
Feel free to.
I used the wiki as a brainstorming sandbox, because it's much faster to write down lots of ideas. (I would have been too lazy to create an issue for every item, and I'm not even sure if all of them deserve their own ticket.)

**Comment by jGleitz** [comment]
That's what this discussion for. I see that editing stuff is faster in the wiki.
If nobody feels the need to move stuff to issues (or doesn't see any advantages), we would be better off leaving things in the wiki.

**Comment by jGleitz** [comment]
Well, I'll just do it.
