### ISSUE TITLE
Matcher/test method for multi-line content with arbitrary order

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#42]
Do we have test method or matcher (if possible) that is given an array of strings and accepts program output that contains all of these lines neglecting their order?
We need something like that in final1 for the `edges` command.

On a side note:
For the `export` command, we probably need to work directly on `TestObject`, since certain lines/whitespace can be optional, so there's probably not much of a reuse value, so we don't need such a method in `InteractiveConsoleTest` but we can just put it in the specific test class (e.g. `ValidNodesCommandTest`).

**Comment by jGleitz** [comment]
Does `test.KitMatchers#containsExactlyDividedBy` fulfil your needs?

Regarding `export`: I already had similar thoughts, too. But that's not a bad thing. `InteractiveConsoleTest` is a helper class for convenience and surely not the mandatory way to test the interactive console.

**Comment by pcworld** [comment]
> Does test.KitMatchers#containsExactlyDividedBy fulfil your needs?

Iirc the divider would be `\n` which doesn't work with the current multiLineTest.
Does it respect the order? Name and documentation currently implies so.

**Comment by jGleitz** [comment]
Ah, I see. I'm working on a better solution.
No, it does not respect order. It requires the exact elements to be contained in any order.

**Comment by pcworld** [comment]
Maybe we could have a `multiLineTest`-like method that takes a `LinkedHashMap<String, Matcher<String>>`, where the keys are the commands and the values matchers that match the correct output. (LinkedHashMap to keep the elements in insertion order.)
This could be used to test commands like `recommend`, `edges` and `export` in one run.

Edit: This would also make it easier to keep track in the code about which command belongs to which output. Currently I have to count to make sure I'm editing the right item in the `getMatchers` method.
Edit 2: A map doesn't make sense, since we can't have duplicate commands.

**Comment by jGleitz** [comment]
You can always feel free to add components and methods to the API! If somebody doesn't like it, he can stilly comment on the pull request.
Anyway, I implemented this in #66. Have a look at it!

**Comment by jGleitz** [comment]
> A map doesn't make sense, since we can't have duplicate commands

Gotcha. Removing the pull

**Comment by pcworld** [comment]
From #65:

> > I really like the doubled-array pattern you chose to build your commands and results. Why don't you put the for loop into a method in InteractiveConsoleTest? It's a pattern worth adapting.
> 
> That String[][] array only allows for is() matchers. That's why I proposed the Map<String, Matcher<String>> method. Isn't there a similar data structure for a "two-dimensional array" array like this, that keeps order and allows for duplicate "keys"?

**Comment by jGleitz** [comment]
I assume this is completly solved with #81 ?

**Comment by pcworld** [comment]
Is there a way to match arbitrary order of the lines currently?

**Comment by jGleitz** [comment]
Oh, no. And that was what this whole issue was about in the first place.
But it's going to be easy to implement a new `Run` for this.

**Comment by jGleitz** [comment]
There it is.
