### ISSUE TITLE
Test invalid ids in recommend terms

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#48]
We should test invalid product ids (chars in ids or ids too large for integers) in recommend terms.

**Comment by pcworld** [comment]
Fixed in d7f8fdff72109120978503ef080c2ef87fc509a6

**Comment by RomanLangrehr** [comment]
@pcworld @jGleitz No, that only added those tests to the data file.
This issue is for the recommend term, where we should test this to.
(Actually I recognized that there is no test for recommend terms right now, after opening this issue, so I started writing this test ;))
