### ISSUE TITLE
Order checks insert ordered

### ISSUE THREAD

**Issue by rapus95** [jGleitz/JUnit-KIT#5]
When i checked my code for B and C all was fine. Then i uploaded it to Praktomat which said "public tests failed"...
Reason was that my traverse modes produced wrongly ordered output...

when i looked into the tests i saw that the inserts were ordered. Thus my code could insert wrongly and thus output wrongly too but it was nevertheless valid (said JUnit)

Same happened for the Books from Task C which only have ordered Input...

Thus i recommend to either shuffle the input for both tests or to (in order to prevent the same problem happening vice versa) add a test in order to have one that checks with sorted input and another one that checks with shuffled input.

**Comment by jGleitz** [comment]
I don't quite understand the issue. I see no insertions that I would call _ordered_. Please elaborate on what you call _ordered_ and in which way the test could run successfully on a wrong implementation. 

The pre order test runs the following commands:

<pre>
"insert Hamburg:10",
"insert Muenchen:30",
"insert Aachen:9",
"insert Zuerich:3",
"info",
"quit"
</pre>

and expects the following output:

<pre>
"Hamburg:10,Aachen:9,Muenchen:30,Zuerich:3"
</pre>

in order test:

<pre>
"insert Hamburg:10",
"insert Muenchen:30",
"insert Aachen:9",
"insert Zuerich:3",
"info",
"quit"
</pre>

correct output:

<pre>
"Aachen:9,Hamburg:10,Muenchen:30,Zuerich:3"
</pre>

level order:

<pre>
"insert Hamburg:10",
"insert Muenchen:30",
"insert Aachen:9",
"insert Zuerich:3",
"insert Aaachen:3",
"info",
"quit"
</pre>

expected output:

<pre>
"Hamburg:10,Aachen:9,Muenchen:30,Aaachen:3,Zuerich:3"
</pre>

**Comment by jGleitz** [comment]
Do you have record of the Praktomat's exact error message for your implementation? What does you code print for the above commands?

**Comment by rapus95** [comment]
Sorry for being that late...
Had problems with my KIT connection... so the problem of the praktomat has been:

> java edu.kit.informatik.teilB.Main 
> insert karlsruhe:299103
> insert mannheim:296690
> insert hamburg:1746342
> insert berlin:3421829
> insert heidelberg:152113
> search heidelberg
> heidelberg:152113
> info
> hamburg:1746342,berlin:3421829,heidelberg:152113,karlsruhe:299103,mannheim:296690
> Expected 'berlin:3421829,hamburg:1746342,heidelberg:152113,karlsruhe:299103,mannheim:296690', but got 'hamburg:1746342,berlin:3421829,heidelberg:152113,karlsruhe:299103,mannheim:296690'
> Skipping the rest
> 
> Time taken: 0.31s
> ![image](https://cloud.githubusercontent.com/assets/5960902/5794431/da259834-9f6c-11e4-859d-5c2b6141da57.png)

the important code has been in the traverseInOrder method:

```
        ...
            if (leftChild != null) {
                leftChild.traversePreOrder(sb);//that was the problem...
               ...
            }

            ...

            if (rightChild != null) {
                ...
                rightChild.traverseInOrder(sb);
            }
        }
```

regarding the code i don't want to make more of it public... if u have a concrete question pm me or skype etc if u write email u should say that here since i usually don't look into my account very often

**Comment by rapus95** [comment]
ok that's pretty strange... i right now tested both, the praktomat version & yours one...
The one of the praktomat produced the same result as copied...
the one of you... produces the same result as you expected... thus... my code sometimes works and sometimes doesn't o.O

**Comment by rapus95** [comment]
Ok it seems that it was due to the tree depth...
your example had a depth of 1 child node on the left side (where i accidentally changed traverse mode) while the one the praktomat had an additional depth... and there my changed mode thus printed in wrong order...

Btw. sorry for blaming u that the input was ordered o.O i was a bit confused when i viewed the test files and messed up the expected result with the input... and the expected result WAS ordered :D

**Comment by jGleitz** [comment]
Okay. I'll close the issue (as it's irrelevant now anyway), but we will remember to test with more elements for the future!

**Comment by jGleitz** [comment]
An no need for being sorry ;)
