### ISSUE TITLE
Empty lines at the end of the input file

### ISSUE THREAD

**Issue by childen** [jGleitz/JUnit-KIT#61]
In my opinion it does not make sense to have a test which checks if trailing empty lines are recognized as the provided FileInputHelper class does not read trailing empty lines. -> Checking it would be complicated if the provided class is used. -> it is very unlikely that it will be checked on.

**Comment by jGleitz** [comment]
We had a long discussion about that already, too. They are not allowed to test against it, as they provided the `FileInputHelper` class. So removing the test is maybe the best way to go.

**Comment by pcworld** [comment]
I went with what they said on ILIAS, empty lines are syntax errors.
I know that it doesn't work together with their provided FileInputHelper (which is implemented in a very _cough_ stupid _cough_ way). If you get them to make an official statement about trailing newlines, I won't complain about removing this test ;)

**Comment by jGleitz** [comment]
I'm writing a post in the moment. Does anybody know whether the `FileInputHelper` outputs multiple trailing newlines?

**Comment by jGleitz** [comment]
[“Leerzeichen am Ende der Datei on“ KIT-ILIAS](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&cmdNode=ed:5v&baseClass=ilRepositoryGUI)

**Comment by childen** [comment]
I tested it. It does not output multiple trailing lines.

**Comment by jGleitz** [comment]
> Der FileInputHelper darf beliebig verändert werden und ist eher als Ausgangspunkt zu verstehen.

Sounds more like we should keep the test…

**Comment by pcworld** [comment]
We can add a comment to the test that explains that failing this test might be a result of using FileInputHelper.

**Comment by jGleitz** [comment]
Nice idea.

**Comment by childen** [comment]
Comment sounds good. 
And just to save everyone who finds this comment some time figuring out what's wrong with the "interesting" implementation in the FileInputHelper: Read this http://stackoverflow.com/questions/545957/java-split-method-strips-empty-strings-at-the-end .

**Comment by jGleitz** [comment]
@childen: I strongly recommend against posting any kind of solutions here. Therefore, I would as well not include such a comment in the code. You might consider editing your comment.

**Comment by childen** [comment]
I would not consider the content of the post a "solution" but I removed the last sentence to make it less obvious ;-). If you are still worried that someone could have a problem with it do whatever you think is right.

**Comment by jGleitz** [comment]
@childen  +1

**Comment by jGleitz** [comment]
Please take note of the discussion in the KIT-ILIAS: [“Leerzeilen in der Eingabedatei”](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=52307&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI). It points out why an official statement is needed, which will hopefully be given there.

**Comment by jGleitz** [comment]
There was an official statement in the ILIAS on this topic. To my knowledge, our tests test the way the Praktomat will. Closing this.
