### ISSUE TITLE
New Eclipse Formatter & Cleanup configuration files

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#63]
The repository now contains `junit-kit-formatter.xml` and `junit-kit-cleanup.kit`, which are configuration files for the Eclipse Formatter and Cleanup tool. 
Please import them into the a project you use for writing the tests and apply them before pushing commits.

This issue is only to make developers notice. Commenting that you've adapted the new configurations are welcome!

**Comment by jGleitz** [comment]
Eclipse's cleanup tool obviously contains bugs. 

How to reproduce: Run the cleanup tool. It will change line 76 of `test.framework.Terminal.java`. Run the cleanup tool again. It will change line 76 again, to the state it was in in the beginning. Run the cleanup once again. You're in state 2 again. 
And so on…

**Comment by pcworld** [comment]
Scratch the cleanup tool then? Formatter probably does most of the things we really need (i.e. consistent formatting).

**Comment by jGleitz** [comment]
Sounds reasonable.
