### ISSUE TITLE
Test 0 prefix for IDs

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#68]
IDs in the form of `0000105` have to be treated as if the leading zeros where not existent. Therefore they have to be 
- accepted
- Treated like their counterparts without leading zeros. Therefore `0000105` has to treated as if it was `105`

There will not be an official test for this behaviour in the `recommend` command, which seems to imply that it won't be tested for the input files, too (But this is my interpretation!).
Anyone implementing this could consider opening a `OptinalRecommendationTest` that runs all mandatory tests and some more that are not required but “nice to have”.

**Comment by jGleitz** [comment]
@RomanLan: I assume this issue is sufficiently tested by #94?

**Comment by RomanLangrehr** [comment]
Yes it is.
