### ISSUE TITLE
Test the edges command

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#70]
The `edges` command has to be asserted to work correctly, of course.

Related: #42

**Comment by jGleitz** [comment]
Please note the different ways for a class to output when implementing this: [KIT-ILIAS: “Ausgabe von Zeilen”](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53450&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI)

**Comment by jGleitz** [comment]
Please note #74 when implementing this.

**Comment by jGleitz** [comment]
Well be significantly easier with #81

**Comment by pcworld** [comment]
Implemented in ece4f79159dfc718132086a97a23b5eb8035adb4 in #65

**Comment by pcworld** [comment]
Closing as no complains were made.
