### ISSUE TITLE
multiLineTests asserts whole output at the end

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#74]
The current behaviour is that `multiLineTest` asserts the whole output of an interactive console session after all commands have been run. It thereby takes exactly one matcher for one call to `Terminal.printLine()`.

But as described in the [KIT-ILIAS topic “Ausgabe von Zeilen”](https://ilias.studium.kit.edu/ilias.php?ref_id=413544&cmdClass=ilobjforumgui&thr_pk=53450&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI), we may not make any assumptions regarding the relation between calls to `Terminal.printLine()` and printed lines.

Therefore, we should run a command, match its output, allowing to join multiple calls to `Terminal.printLine`, but also allowing to keep them separated, [as required for error messages](https://ilias.studium.kit.edu/ilias.php?ref_id=366572&cmdClass=ilobjforumgui&thr_pk=51401&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI). After the output has been matched, the next command can be run, which then afterwards can be matched. And so on.

Solving this requires major changes in the way `InteractiveConsoleTest` works and interacts with `TestObject`. We could take this as a chance to change so API functionalities, too. For example are a lot functions already provided by different classes of the framework, meanwhile, they are always accessed through `TestObject`. It's worth discussion whether this is a well designed pattern.

Until this is fixed, we'll assume that one command results in one call to `Terminal.printLine()`, which should match the way most people do it.

**Comment by pcworld** [comment]
Thanks for clarifying how this currently works.

> Until this is fixed, we'll assume that one command results in one call to Terminal.printLine(), which should match the way most people do it.

I personally currently do a Terminal.printLine for every output line of the `edges` command.

To test `edges`/`export`, we could work around this by working directly on TestObject and e.g. splitting all strings of #getLastMethodsOutput that contain a newline. This would avoid the need for a framework refactoring.

**Comment by jGleitz** [comment]
> I personally currently do a Terminal.printLine for every output line of the edges command.

Bummer. I hoped we could move this until after Monday.

>  we could work around this by working directly on TestObject 

I hope that refactoring the framework does not require significant more work than writing a method for the behaviour.
