### ISSUE TITLE
final1: Test for product ID 0 and negative numbers

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#77]
0 valid, negative numbers (i.e. preceeded with a dash) invalid.
0 is currently tested as input in #65. (We could create a simple 0 test though.)
Also test 0 as ID for `recommend` command.

**Comment by jGleitz** [comment]
+1 for adding simple tests for all these cases.

**Comment by pcworld** [comment]
Fixed by 6f631fe546e9055fd155f29b2523f0a9d856530b in #65.

**Comment by jGleitz** [comment]
Seems like we really should merge #65 soon :)

The new syntax is getting bigger than I thought. But I'm still positive I'll finish it today.
