### ISSUE TITLE
LineRun#check: System.lineSeparator

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#83]
Could be problematic when tests are run on Windows with a program that hardcodes linebreaks as `\n`.
See [this discussion](https://github.com/jGleitz/JUnit-KIT/pull/81#discussion-diff-26423487)

**Comment by jGleitz** [comment]
> My "hacky" approach would be:
> 
> ```
> mergedOutputBuilder.append(output.replaceAll("\r", ""));
> mergedOutputBuilder.append("\n");
> ...
> String[] outputLines = mergedOutputBuilder.toString().split("\n");
> ```

Yep, I actually think that's the best solution.
