### ISSUE TITLE
Check AND and OR to be upper case

### ISSUE THREAD

**Issue by jGleitz** [jGleitz/JUnit-KIT#9]
In search terms, `AND` and `OR` have to be all upper case. Any other writing, like `and` or `Or` should print an error message.

**Comment by MartinLoeper** [comment]
Is this really necessary?
The task states that all comparisons are case insensitive.

**Comment by RomanLangrehr** [comment]
Yes.
All comparisons should be made case insensitve, so we need to test wheather they really are case insensitive.

**Comment by jGleitz** [comment]
The exact wording you are refering to is "Alle Vergleiche bei allen
Zeichenketten in dieser Aufgabe erfolgen ohne Beachtung der Klein- oder Großschreibung."

I would not have considered the detection of `OR` and `AND` as a "Vergleich bei einer Zeichenkette". Plus, these are the only to Strings that have the same case throughout the task sheet. Thus, my assumption. 

Nevertheless, I see your arguments. Is there a chance that I am right (and maybe we should ask on ILIAS) or am I completly mistaken at this one?

**Comment by MartinLoeper** [comment]
I implemented the exact wording replacing every equals with equalsIgnoreCase and adding the Pattern.CASE_INSENSITIVE flag for regex. So every String is compared case insensitive as required by the task.
But I see thanks to your arguments that this might not be Philipp Merkle's intention... Should we ask on Ilias?

**Comment by jGleitz** [comment]
As I said, I know what you mean. And yes, it might bee that this was not what was intended. I'll post an ILIAS question.

**Comment by jGleitz** [comment]
The [question on ILIAS](https://ilias.studium.kit.edu/ilias.php?ref_id=366572&cmdClass=ilobjforumgui&thr_pk=51436&cmd=viewThread&cmdNode=ed:5v&baseClass=ilRepositoryGUI)

**Comment by jGleitz** [comment]
All right, you were right, I was wrong, closing this as invalid.
