### ISSUE TITLE
Some files are not deleted

### ISSUE THREAD

**Issue by RomanLangrehr** [jGleitz/JUnit-KIT#92]
When running the test (without stopping it in between ;) ), there are 6 generated files left on my hard drive, that are not deleted after the test finished.

At the moment, all tests are successful except the ValidNodesCommandTest#oneLineTest (and the incomplete annotations of course).

**Comment by jGleitz** [comment]
Does this happen reliably?

**Comment by RomanLangrehr** [comment]
Yes, every time I run the test...

**Comment by jGleitz** [comment]
That's a shame, because I can't reproduces this on my machine. 

Do you have any spare time to debug it?

**Comment by RomanLangrehr** [comment]
In a few minutes - I have to recreate my repository first ;)

**Comment by RomanLangrehr** [comment]
Recreating my repository fixed this ;)
