### ISSUE TITLE
Merge with master

### ISSUE THREAD

**Issue by pcworld** [jGleitz/JUnit-KIT#97]
Most remaining issues either depend on official statements (which may or may not be made) or require relatively trivial changes (e.g. testing with different edge types).
I think we should be able to merge with master now. Thoughts?

**Comment by jGleitz** [comment]
Great minds think alike.  :D

See my comments on #95. I'm corrently re-reading everything we have on the task sheet and compare with what we have so far. I'd plead for removing `incomplete` and merging with `master` afterwards.

**Comment by RomanLangrehr** [comment]
Me too, especially for removing the incomplete annotations...

**Comment by pcworld** [comment]
> Me too, especially for removing the incomplete annotations...

Has already been merged into development

**Comment by jGleitz** [comment]
#100
